# JULEA - Flexible storage framework
# Copyright (C) 2021 Michael Kuhn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Dependencies
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  dependencies:
    name: Dependencies
    runs-on: ${{ matrix.os.dist }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        os:
          - dist: ubuntu-22.04
            compiler: gcc
            compiler_version: 11.2.0
          - dist: ubuntu-22.04
            compiler: clang
            compiler_version: 14.0.0
          - dist: ubuntu-20.04
            compiler: gcc
            compiler_version: 9.4.0
          - dist: ubuntu-20.04
            compiler: clang
            compiler_version: 11.0.0
          - dist: ubuntu-18.04
            compiler: gcc
            compiler_version: 7.5.0
          - dist: ubuntu-18.04
            compiler: clang
            compiler_version: 9.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies
        env:
          JULEA_SPACK_COMPILER: ${{ matrix.os.compiler }}@${{ matrix.os.compiler_version }}
        run: |
          ./scripts/install-dependencies.sh
